name: Run OCI Script

on:
  schedule:
    - cron: "*/2 * * * *"   # Cada 5 minutos
  workflow_dispatch:        # Para ejecutarlo manualmente

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar PHP
        run: sudo apt-get install -y php php-curl php-cli

      - name: Instalar dependencias (Composer)
        run: composer install

      - name: Ejecutar script
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_PATH: oci_key.pem
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
        run: php index.php

